# Generated by Django 4.2.4 on 2024-12-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                (
                    "availability",
                    models.CharField(
                        choices=[("FT", "Full-Time"), ("PT", "Part-Time")],
                        default="FT",
                        max_length=2,
                    ),
                ),
                ("department", models.CharField(max_length=255)),
            ],
        ),
    ]
